name: giphy_get
description: Pick EMOJI,STICKER or GIF from Giphy in pure dart code. Support Android,iOS,Web and Desktop.
version: 3.5.0
publish_to: none
homepage: https://github.com/bazookon/giphy_get

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  extended_image:
    git: https://github.com/nordify/zaap_extended_image.git

  provider: ^6.0.5
  flutter_staggered_grid_view: ^0.7.0
  meta: ^1.9.1
  http: ^0.13.5
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.2
  pedantic: ^1.11.1
  matcher: ^0.12.15

flutter:
  assets:
    - assets/img/GIPHY_dark.png
    - assets/img/GIPHY_light.png
    - assets/img/poweredby_dark.png
    - assets/img/poweredby_light.png
